### ISSUE TITLE
2021-07-19 errorReport

### ISSUE THREAD

**Issue by Gyoung-min** [Gyoung-min/javaStudy#76]
## 부적합한 열 유형 11111

- 에러 메시지는 다음과 같습니다.

```
java.sql.SQLException: 부적합한 열 유형: 1111
	at oracle.jdbc.driver.OracleStatement.getInternalType(OracleStatement.java:4469) ~[ojdbc8-21.1.0.0.jar:21.1.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatement.setNullCritical(OraclePreparedStatement.java:4382) ~[ojdbc8-21.1.0.0.jar:21.1.0.0.0]
	at oracle.jdbc.driver.OraclePreparedStatement.setNull(OraclePreparedStatement.java:4366) ~[ojdbc8-21.1.0.0.jar:21.1.0.0.0]
~~~~
```

- 전체 코드는 다음과 같습니다.
  - buttonPage
```
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
<h1>버튼page</h1>

<form action="favoritesInsert" method="POST">
<button type="submit" value="2,ani1" name="data">추가</button>
</form>

<form action="favoritesDelete" method="POST">
<button type="submit" value="2,ani1" name="data">삭제</button>
</form>


</body>
</html>
```
  - favoritesMainPage
```
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>

<h1>DBtest</h1>
<table border="2">
	<tr><th>유저넘버</th><th>저장즐겨찾기</th></tr>
	<c:forEach var="test" items="${favoritesMainPage}">
		<tr>
			<th>${test.wish_user_no}</th>
			<th>${test.con_no}</th>
		</tr>
	</c:forEach>
</table>

<c:forEach var="test" items="${favoritesMainPage}">
<img src = "${test.con_no}"/>

</c:forEach>



<div>${test.wish_user_no}</div>


</body>
</html>
```
  - FavoritesController
```
package com.kgflix.favorites;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.kgflix.favorites.dao.FavoritesDAO;

@Controller
public class FavoritesController {
	
	@Autowired
	FavoritesDAO dao;
	
	

	@RequestMapping("/")
	public String setButton() {

		return "buttonPage";
	}

	
	
	@RequestMapping("/favoritesMainPage")
	public String favoritesMainPage(Model model) {
		model.addAttribute("favoritesMainPage",dao.getAllInfo());

		System.out.println(model);
		
		return "favoritesMainPage";
	}
	
	@RequestMapping(value="favoritesInsert", method = RequestMethod.POST)
	public String insertFavorites(HttpServletRequest req) {
		String data = req.getParameter("data");
		String [] wishData = data.split(",");
		String wish_user=wishData[0];//2
		int wish_user_no = Integer.parseInt(wish_user);
		String con_no=wishData[1];//ANI1
		dao.insertFavorites(wish_user_no, con_no+".png");
		
		
		return "redirect:favoritesMainPage";
	}
	
	
	@RequestMapping(value="favoritesDelete", method = RequestMethod.POST)
	public String deleteFavorites(HttpServletRequest req) {
		String data = req.getParameter("data");
		String [] wishData = data.split(",");
		String wish_user_no=wishData[0];
		String con_no=wishData[1];
		dao.deleteFavorites(wish_user_no, con_no+".png");
		
		return "redirect:favoritesMainPage";
	}

}
```
  - FavoritesDAO
```
package com.kgflix.favorites.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.kgflix.favorites.vo.FavoritesVO;

@Mapper
public interface FavoritesDAO {
	public List<FavoritesVO>getAllInfo();
	public void insertFavorites(int wish_user_no, String con_no);//
	public void deleteFavorites(String wish_user_no, String con_no);
}

```
  - FavoritesVO
```
package com.kgflix.favorites.vo;

import lombok.Data;

@Data
public class FavoritesVO {
	private int wish_user_no;
	private String con_no;
	
	private String id;
	private String name;
}
```
  - favoritesMapper.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.kgflix.favorites.dao.FavoritesDAO">

<select id = "getAllInfo" resultType="com.kgflix.favorites.vo.FavoritesVO">

SELECT user_table.id, user_table.name, wish_table.wish_user_no, wish_table.con_no FROM user_table
    INNER JOIN wish_table
    ON user_table.user_no = wish_table.wish_user_no
	WHERE user_table.user_no = wish_table.wish_user_no
</select>

<insert id="insertFavorites">

INSERT INTO wish_table (wish_user_no, con_no) 
SELECT #{wish_user_no}, #{con_no} FROM DUAL
WHERE NOT EXISTS
(SELECT wish_user_no, con_no FROM wish_table
WHERE wish_user_no = #{wish_user_no} AND con_no = #{con_no})
</insert>

<delete id = "deleteFavorites">
DELETE FROM wish_table WHERE wish_user_no = #{wish_user_no} AND con_no = #{con_no}
</delete>

</mapper>
```

## 오류의 원인

- favoritesMapper.xml 에 WHERE 추가 조건을 넣을시 발생
  - WHERE 추가 조건이 없으면 다음과 같이 정상 작동 됨을 확인 할수 있습니다.
    - 버튼 페이지에서 추가를 누르면
![버튼](https://user-images.githubusercontent.com/78856207/126091232-34fa3686-ac2d-4c2c-861c-3d3b4013d41a.PNG)
    - 2번째 행이 추가됨
![FAVORITEPA](https://user-images.githubusercontent.com/78856207/126091288-2f362bd0-6304-4f40-b097-5cec906a05f5.PNG)

    - 삭제 버튼을 누르면
![버튼](https://user-images.githubusercontent.com/78856207/126091336-ef327b88-760e-4f6c-8e6f-b73f983a2ede.PNG)

    - 2번째 행이 삭제됨
![FAVORITEPA2](https://user-images.githubusercontent.com/78856207/126091450-8e508f47-e238-4050-8c89-24f79d17e43f.PNG)

## WHERE 조건의 목적
- WHERE 조건을 넣지 않으면 유저 넘버가 구분되지 않고 모두 출력됨, 하지만 WHERE user_table.user_no = wish_table.wish_user_no; 조건을 추가함으로 user_table.user_no와 wish_table.wish_user_no이 같은 데이터만 출력해서 결과적으로는 추가를 클릭시 유저 2번에 속한 데이터만 출력되도록 만들어야 함. 그렇게 만들면 즐겨찾기를 구현할 수 있게 된다.

**Comment by Gyoung-min** [comment]
## 문제 해결

```
	@RequestMapping(value="favoritesInsert", method = RequestMethod.POST)
	public String insertFavorites(HttpServletRequest req) {
		String data = req.getParameter("data");
		String [] wishData = data.split(",");
		String wish_user=wishData[0];//2
		int wish_user_no = Integer.parseInt(wish_user);
		String con_no=wishData[1];//ANI1
		dao.insertFavorites(wish_user_no, con_no+".png");
		
		
		return "redirect:favoritesMainPage";
	}
```
- 해당 명령어를 수행 한 후 DB에 다음과 같이 접근한다.

<insert id="insertFavorites">

```
INSERT INTO wish_table (wish_user_no, con_no) 
SELECT #{wish_user_no}, #{con_no} FROM DUAL
WHERE NOT EXISTS
(SELECT wish_user_no, con_no FROM wish_table
WHERE wish_user_no = #{wish_user_no} AND con_no = #{con_no})
</insert>
```
- 그러면 wish_user_no가 고정값을 가지게 됨으로 where 명령어가 수행되지 않는다. 즉 고정값이 아닌 변수를 따로 넘겨주어야 한다. 해결 방법은 다음과 같다

`static int wish_user_no2;`

- 전역 변수 선언 후 전역 변수에 입력받게 될 것을 넣는다.

`wish_user_no2 = Integer.parseInt(wish_user);`

- getAllInfo로 해당 값을 보낸다

`model.addAttribute("favoritesMainPage",dao.getAllInfo(wish_user_no2));`
